#!/bin/bash

function help/palotai() {
  cat << EOF
Warning iTunes tends to crash on large pls import.
EOF
  exit 1
}

url="http://www.palotai.hu/mixek.html"
ppt="playlist"
_ok=".ready"
_v=""

# args
while getopts vhu:p: opt; do
  case "$opt" in
    u) url=$OPTARG;;
    p) ppt=$OPTARG;;
    v) _v="-v";;
    *|h) help/palotai;;
  esac
done

### main
for p in \
$(curl -s "${url}" \
| grep "${ppt}" \
| awk '{gsub(/^.*\('\''/,"");gsub(/'\''.*/,"");print}')
do
  bnp=$(basename "${p%%.html}")
  prev=""
  if test -r "${bnp}/${_ok}"
  then
    continue
  fi
  if ! test -d "${bnp}" ; then
    mkdir ${_v} "${bnp}"
  fi
  cd "${bnp}"
  for m in \
  $(curl -s -L "${p}" \
  | grep "mp3\|ogg" \
  | awk '{gsub(/.*href="/,"");gsub(/".*/,"");print}')
  do
    if ! test "${prev}" = "${m}"
    then
      wget ${_v} -c "${m}"
      prev="${m}"
    fi
    touch "${_ok}"
  done
  cd ..
done
